// Vue/Horizontal/src/components/footer.vue
<script>
export default {
  components: {},
}
</script>

<template>
  <!-- Footer Start -->
  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          2015 - 2019 &copy; UBold theme by
          <a href="javascript: void(0);">Coderthemes</a>
        </div>
        <div class="col-md-6">
          <div class="text-md-right footer-links d-none d-sm-block">
            <a href="javascript:void(0);">About Us</a>
            <a href="javascript:void(0);">Help</a>
            <a href="javascript:void(0);">Contact Us</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- end Footer -->
</template>

// Getting Started Projects/React/Vertical/src/components/Footer.js
import React, { Component } from 'react';

/**
 * Renders the Footer
 */
class Footer extends Component {

    render() {
        return (
            <footer className="footer">
                <div className="container-fluid">
                    <div className="row">
                        <div className="col-md-6">
                            2016 - 2019 &copy; Ubold theme by <a href="https://coderthemes.com">Coderthemes</a>
                        </div>
                        <div className="col-md-6">
                            <div className="text-md-right footer-links d-none d-sm-block">
                                <a href="https://coderthemes.com">About Us</a>
                                <a href="https://coderthemes.com">Help</a>
                                <a href="https://coderthemes.com">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        )
    }
}

export default Footer;
