// Vue/Horizontal/src/router/views/charts/chartjs.vue
<script>
import appConfig from '@src/app.config'
import Layout from '@layouts/main'
import PageHeader from '@components/page-header'

import BarChart from './BarChart'
import LineChart from './LineChart'
import PieChart from './PieChart'
import DonutChart from './DonutChart'
import PolarChart from './PolarChart'
import RadarChart from './RadarChart'

/**
 * Chart-js chart component
 */
export default {
  page: {
    title: 'Chartjs',
    meta: [{ name: 'description', content: appConfig.description }],
  },
  components: {
    Layout,
    PageHeader,
    BarChart,
    LineChart,
    PieChart,
    DonutChart,
    PolarChart,
    RadarChart,
  },
  data() {
    return {
      title: 'Chartjs',
      items: [
        {
          text: 'UBold',
          href: '/',
        },
        {
          text: 'Charts',
          href: '/',
        },
        {
          text: 'Chartjs',
          active: true,
        },
      ],
    }
  },
}
</script>

<template>
  <Layout>
    <PageHeader :title="title" :items="items" />
    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Line Chart</h4>
            <!-- Line Chart -->
            <LineChart :height="350"/>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Bar Chart</h4>
            <!-- Bar Chart -->
            <BarChart :height="350"/>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Pie Chart</h4>
            <!-- Pie Chart -->
            <PieChart :height="170"/>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Donut Chart</h4>
            <!-- Donut Chart -->
            <!-- <canvas id="donut-chart"></canvas> -->
            <DonutChart :height="170"/>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Polar area Chart</h4>
            <!-- Polar area Chart -->
            <PolarChart :height="170"/>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="header-title mb-4">Radar Chart</h4>
            <!-- Radar Chart -->
            <RadarChart :height="170"/>
          </div>
        </div>
      </div>
    </div>
  </Layout>
</template>

// Angular/horizontal/src/app/pages/chart/chartjs/chartjs.component.ts
import { Component, OnInit } from '@angular/core';

import { ChartType } from './chartjs.model';

import { lineAreaChart, lineBarChart, pieChart, donutChart, radarChart, reportChart } from './data';

@Component({
  selector: 'app-chartjs',
  templateUrl: './chartjs.component.html',
  styleUrls: ['./chartjs.component.scss']
})

/**
 * Chartjs component - handling the chartjs chart with navbar and content
 */
export class ChartjsComponent implements OnInit {

  // bread crumb items
  breadCrumbItems: Array<{}>;

  // Line Chart
  lineAreaChart: ChartType;
  // Bar Chart
  lineBarChart: ChartType;
  // Pie Chart
  pieChart: ChartType;
  // Donut Chart
  donutChart: ChartType;
  // Polar area Chart
  ScatterChart: ChartType;
  // Radar Chart
  radarChart: ChartType;
  // Financial Report
  reportChart: ChartType;

  constructor() { }

  ngOnInit() {
    this.breadCrumbItems = [{ label: 'UBold', path: '/' }, { label: 'Charts', path: '/' }, { label: 'Chartjs', path: '/', active: true }];

    /**
     * fetches data
     */
    this._fetchData();
  }

  /**
   * fetches the chartjs data
   */
  private _fetchData() {
    // Line Chart data
    this.lineAreaChart = lineAreaChart;
    // Bar Chart data
    this.lineBarChart = lineBarChart;
    // Pie Chart data
    this.pieChart = pieChart;
    // Donut Chart
    this.donutChart = donutChart;

    // Radar Chart data
    this.radarChart = radarChart;
    // Financial Report
    this.reportChart = reportChart;
  }

}

<div class="container-fluid">
  <app-page-title title="Chartjs" [breadcrumbItems]="breadCrumbItems"></app-page-title>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Line Chart</h4>
          <div class="mt-4 chartjs-chart">
            <!-- Line Chart -->
            <canvas baseChart height="350" [datasets]="lineAreaChart.datasets" [labels]="lineAreaChart.labels"
              [options]="lineAreaChart.options" chartType="line">
            </canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Bar Chart</h4>

          <div class="mt-4 chartjs-chart">
            <!-- Bar Chart -->
            <canvas baseChart [datasets]="lineBarChart.datasets" chartType="bar" [options]="lineBarChart.options"
              height="350" [labels]="lineBarChart.labels">
            </canvas>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Pie Chart</h4>
          <div class="mt-4 chartjs-chart">
            <!-- Line Chart -->
            <canvas baseChart [datasets]="pieChart.datasets" chartType="pie" [options]="pieChart.options" height="350">
            </canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Donut Chart</h4>

          <div class="mt-4">
            <!-- Bar Chart -->
            <canvas baseChart [datasets]="donutChart.datasets" chartType="doughnut" [options]="donutChart.options"
              height="350">
            </canvas>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Financial Report</h4>

          <div class="mt-4 chartjs-chart">
            <!-- Financial report Chart -->

            <canvas baseChart [datasets]="reportChart.datasets" [labels]="reportChart.labels"
              [options]="reportChart.options" chartType="line" height="150"></canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title">Radar Chart</h4>

          <div class="mt-4 chartjs-chart mb-3">
            <!-- Radar Chart -->
            <canvas baseChart [datasets]="radarChart.datasets" chartType="radar" [options]="radarChart.options"
              height="360" [labels]="radarChart.labels">
            </canvas>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
