// Getting Started Projects/React/Horizontal/src/components/Topbar.js
import React, { Component } from "react";
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import classNames from 'classnames';
import { UncontrolledDropdown, DropdownMenu, DropdownToggle, DropdownItem, Container } from 'reactstrap';

import NotificationDropdown from './NotificationDropdown';
import ProfileDropdown from './ProfileDropdown';
import logoSm from '../assets/images/logo-sm.png';
import logo from '../assets/images/logo-dark.png';
import profilePic from '../assets/images/users/user-1.jpg';


const Notifications = [{
  id: 1,
  text: 'Caleb Flakelar commented on Admin',
  subText: '1 min ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'primary'
},
{
  id: 2,
  text: 'New user registered.',
  subText: '5 min ago',
  icon: 'mdi mdi-account-plus',
  bgColor: 'info'
},
{
  id: 3,
  text: 'Cristina Pride',
  subText: 'Hi, How are you? What about our next meeting',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'success'
},
{
  id: 4,
  text: 'Caleb Flakelar commented on Admin',
  subText: '2 days ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'danger'
},
{
  id: 5,
  text: 'Caleb Flakelar commented on Admin',
  subText: '1 min ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'primary'
},
{
  id: 6,
  text: 'New user registered.',
  subText: '5 min ago',
  icon: 'mdi mdi-account-plus',
  bgColor: 'info'
},
{
  id: 7,
  text: 'Cristina Pride',
  subText: 'Hi, How are you? What about our next meeting',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'success'
},
{
  id: 8,
  text: 'Caleb Flakelar commented on Admin',
  subText: '2 days ago',
  icon: 'mdi mdi-comment-account-outline',
  bgColor: 'danger'
}];

const ProfileMenus = [{
  label: 'My Account',
  icon: 'fe-user',
  redirectTo: "/",
},
{
  label: 'Settings',
  icon: 'fe-settings',
  redirectTo: "/"
},
{
  label: 'Lock Screen',
  icon: 'fe-lock',
  redirectTo: "/"
},
{
  label: 'Logout',
  icon: 'fe-log-out',
  redirectTo: "/logout",
  hasDivider: true
}]


class Topbar extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }


  render() {
    return (
      <React.Fragment>
        <div className="navbar-custom">
          <Container fluid>
            <ul className="list-unstyled topnav-menu float-right mb-0">

            <li className="dropdown notification-list">
                <Link className={classNames('navbar-toggle', 'nav-link', {'open': this.props.isMenuOpened})} to="#" onClick={this.props.menuToggle}>
                    <div className="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </Link>
            </li>

              <li className="d-none d-sm-block">
                <form className="app-search">
                  <div className="app-search-box">
                    <div className="input-group">
                      <input type="text" className="form-control" placeholder="Search..." />
                      <div className="input-group-append">
                        <button className="btn" type="submit">
                          <i className="fe-search"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </form>
              </li>

              <li>
                <NotificationDropdown notifications={Notifications} />
              </li>

              <li>
                <ProfileDropdown profilePic={profilePic} menuItems={ProfileMenus} username={'Nik Patel'} />
              </li>


              <li className="dropdown notification-list">
                <button className="btn btn-link nav-link right-bar-toggle waves-effect waves-light" onClick={this.props.rightSidebarToggle}>
                  <i className="fe-settings noti-icon"></i>
                </button>
              </li>
            </ul>

            <div className="logo-box">
              <Link to="/" className="logo text-center">
                <span className="logo-lg">
                  <img src={logo} alt="" height="18" />
                </span>
                <span className="logo-sm">
                  <img src={logoSm} alt="" height="24" />
                </span>
              </Link>
            </div>

            <ul className="list-unstyled topnav-menu topnav-menu-left m-0">
              <li className="dropdown d-none d-lg-block">
                <UncontrolledDropdown>
                  <DropdownToggle
                    data-toggle="dropdown"
                    tag="button"
                    className="btn btn-link nav-link dropdown-toggle waves-effect waves-light">
                    Create New
                    <i className="mdi mdi-chevron-down"></i>
                  </DropdownToggle>
                  <DropdownMenu right className="dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                    <Link to="/" className="dropdown-item">
                      <i className="fe-briefcase mr-1"></i>
                      <span>New Projects</span>
                    </Link>
                    <Link to="/" className="dropdown-item">
                      <i className="fe-user mr-1"></i>
                      <span>Create Users</span>
                    </Link>
                    <Link to="/" className="dropdown-item">
                      <i className="fe-bar-chart-line- mr-1"></i>
                      <span>Revenue Report</span>
                    </Link>
                    <Link to="/" className="dropdown-item">
                      <i className="fe-settings mr-1"></i>
                      <span>Settings</span>
                    </Link>
                    <DropdownItem divider />
                    <Link to="/" className="dropdown-item">
                      <i className="fe-headphones mr-1"></i>
                      <span>Help & Support</span>
                    </Link>
                  </DropdownMenu>
                </UncontrolledDropdown>
              </li>
            </ul>
          </Container>
        </div>
      </React.Fragment >
    );
  }
}


export default connect()(Topbar);

// Vue/Horizontal/src/components/top-bar.vue
<script>
import { authComputed } from '@state/helpers'
import VuePerfectScrollbar from 'vue-perfect-scrollbar'

export default {
  components: { VuePerfectScrollbar },
  props: {
    user: {
      type: Object,
      required: false,
      default: () => ({}),
    },
    isMenuOpened: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  data() {
    return {}
  },
  computed: {
    ...authComputed,
  },
  methods: {
    toggleMenu() {
      this.$parent.toggleMenu()
    },
    toggleRightSidebar() {
      this.$parent.toggleRightSidebar()
    },
  },
}
</script>

<template>
  <!-- Topbar Start -->
  <div class="navbar-custom">
    <div class="container-fluid">
      <ul class="list-unstyled topnav-menu float-right mb-0">
        <li class="dropdown notification-list">
          <a
            class="navbar-toggle nav-link"
            :class="{ 'open': isMenuOpened }"
            @click="toggleMenu"
          >
            <div class="lines">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </a>
        </li>

        <li class="d-none d-sm-block">
          <form class="app-search">
            <div class="app-search-box">
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Search..."
                />
                <div class="input-group-append">
                  <button
                    class="btn"
                    type="submit"
                  >
                    <i class="fe-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </li>

        <b-nav-item-dropdown
          right
          class="notification-list"
        >
          <template
            slot="button-content"
            class="nav-link dropdown-toggle"
          >
            <i class="fe-bell noti-icon"></i>
            <span class="badge badge-danger rounded-circle noti-icon-badge">9</span>
          </template>

          <b-dropdown-text
            href="#"
            class="dropdown-item noti-title"
          >
            <h5 class="m-0">
              <span class="float-right">
                <a
                  href
                  class="text-dark"
                >
                  <small>Clear All</small>
                </a>
              </span>Notification
            </h5>
          </b-dropdown-text>

          <b-dropdown-text
            href="#"
            class="p-0"
          >
            <VuePerfectScrollbar
              v-once
              class="noti-scroll"
            >
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item active"
              >
                <div class="notify-icon">
                  <img
                    src="@assets/images/users/user-1.jpg"
                    class="img-fluid rounded-circle"
                    alt
                  />
                </div>
                <p class="notify-details">Cristina Pride</p>
                <p class="text-muted mb-0 user-msg">
                  <small>Hi, How are you? What about our next meeting</small>
                </p>
              </a>

              <!-- item-->
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item"
              >
                <div class="notify-icon bg-primary">
                  <i class="mdi mdi-comment-account-outline"></i>
                </div>
                <p class="notify-details">
                  Caleb Flakelar commented on Admin
                  <small class="text-muted">1 min ago</small>
                </p>
              </a>

              <!-- item-->
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item"
              >
                <div class="notify-icon">
                  <img
                    src="@assets/images/users/user-4.jpg"
                    class="img-fluid rounded-circle"
                    alt
                  />
                </div>
                <p class="notify-details">Karen Robinson</p>
                <p class="text-muted mb-0 user-msg">
                  <small>Wow ! this admin looks good and awesome design</small>
                </p>
              </a>

              <!-- item-->
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item"
              >
                <div class="notify-icon bg-warning">
                  <i class="mdi mdi-account-plus"></i>
                </div>
                <p class="notify-details">
                  New user registered.
                  <small class="text-muted">5 hours ago</small>
                </p>
              </a>

              <!-- item-->
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item"
              >
                <div class="notify-icon bg-info">
                  <i class="mdi mdi-comment-account-outline"></i>
                </div>
                <p class="notify-details">
                  Caleb Flakelar commented on Admin
                  <small class="text-muted">4 days ago</small>
                </p>
              </a>

              <!-- item-->
              <a
                href="javascript:void(0);"
                class="dropdown-item notify-item"
              >
                <div class="notify-icon bg-secondary">
                  <i class="mdi mdi-heart"></i>
                </div>
                <p class="notify-details">
                  Carlos Crouch liked
                  <b>Admin</b>
                  <small class="text-muted">13 days ago</small>
                </p>
              </a>
            </VuePerfectScrollbar>

            <a
              href="javascript:void(0);"
              class="dropdown-item text-center text-primary notify-item notify-all"
            >
              View all
              <i class="fi-arrow-right"></i>
            </a>
          </b-dropdown-text>
        </b-nav-item-dropdown>

        <b-nav-item-dropdown
          right
          class="notification-list"
          menu-class="profile-dropdown"
        >
          <template slot="button-content">
            <div class="nav-user mr-0">
              <img
                src="@assets/images/users/user-1.jpg"
                alt="user-image"
                class="rounded-circle"
              />
              <span class="pro-user-name ml-1">
                {{user ? user.name : ''}}
                <i class="mdi mdi-chevron-down"></i>
              </span>
            </div>
          </template>

          <b-dropdown-item href="#">
            <i class="fe-user mr-1"></i>
            <span>My Account</span>
          </b-dropdown-item>

          <b-dropdown-item href="#">
            <i class="fe-settings mr-1"></i>
            <span>Settings</span>
          </b-dropdown-item>

          <b-dropdown-item href="#">
            <i class="fe-lock mr-1"></i>
            <span>Lock Screen</span>
          </b-dropdown-item>

          <b-dropdown-divider></b-dropdown-divider>
          <b-dropdown-item href="/logout">
            <i class="fe-log-out mr-1"></i>
            <span>Logout</span>
          </b-dropdown-item>
        </b-nav-item-dropdown>

        <li class="dropdown notification-list">
          <button
            class="btn btn-link nav-link right-bar-toggle toggle-right"
            @click="toggleRightSidebar"
          >
            <i class="fe-settings noti-icon toggle-right"></i>
          </button>
        </li>
      </ul>

      <!-- LOGO -->
      <div class="logo-box">
        <a
          href="index.html"
          class="logo text-center"
        >
          <span class="logo-lg">
            <img
              src="@assets/images/logo-dark.png"
              alt
              height="18"
            />
          </span>
          <span class="logo-sm">
            <img
              src="@assets/images/logo-sm.png"
              alt
              height="24"
            />
          </span>
        </a>
      </div>

      <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <b-nav-item-dropdown
          class="d-none d-lg-block"
          right
        >
          <template slot="button-content">
            Create New
            <i class="mdi mdi-chevron-down"></i>
          </template>
          <b-dropdown-item href="#">
            <i class="fe-briefcase mr-1"></i>
            <span>New Projects</span>
          </b-dropdown-item>
          <b-dropdown-item href="#">
            <i class="fe-user mr-1"></i>
            <span>Create Users</span>
          </b-dropdown-item>
          <b-dropdown-item href="#">
            <i class="fe-bar-chart-line- mr-1"></i>
            <span>Revenue Report</span>
          </b-dropdown-item>
          <b-dropdown-item href="#">
            <i class="fe-settings mr-1"></i>
            <span>Settings</span>
          </b-dropdown-item>
          <b-dropdown-item href="#">
            <i class="fe-headphones mr-1"></i>
            <span>Help & Support</span>
          </b-dropdown-item>
        </b-nav-item-dropdown>
      </ul>
    </div>
  </div>
  <!-- end Topbar -->
</template>

<style lang="scss">
.noti-scroll {
  height: 220px;
}
.ps > .ps__scrollbar-y-rail {
  width: 8px !important;
  background-color: transparent !important;
}
.ps > .ps__scrollbar-y-rail > .ps__scrollbar-y,
.ps.ps--in-scrolling.ps--y > .ps__scrollbar-y-rail > .ps__scrollbar-y,
.ps > .ps__scrollbar-y-rail:active > .ps__scrollbar-y,
.ps > .ps__scrollbar-y-rail:hover > .ps__scrollbar-y {
  width: 6px !important;
}
.button-menu-mobile {
  outline: none !important;
}
</style>
